### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by philipp-spiess** [philipp-spiess/react-recomponent#12]
We should consider adding TypeScript definitions before the `1.0.0` release. 

However, I have not worked a lot with TypeScript so far. If anyone has experience with it, I would really appreciate your help.

**Comment by nataly87s** [comment]
I would like to work on this issue

**Comment by philipp-spiess** [comment]
@nataly87s This is awesome! Thank you so much for your help - please feel free to reach out if you need any help and I will see what I can do 😊

**Comment by nataly87s** [comment]
@philipp-spiess where do you want me to put the declaration file? under `type-definitions` folder?

**Comment by philipp-spiess** [comment]
Thank you for your help 🎉 

There are two follow up tasks that we need to tackle:

1. We need to make sure that the TypeScript declarations are part of the released npm package and are recognized by the TypeScript compiler. 
2. It would be great to add some tests as well.

If nobody knows better I'd take a look at the Immutable.js repository and see how they implemented this.

**Comment by nataly87s** [comment]
I can do both tomorrow

**Comment by nataly87s** [comment]
@philipp-spiess I'm working on the tests. anything specific you want to test, or are exported types enough?

**Comment by nataly87s** [comment]
did you consider moving the `reducer` method to the class instance instead of a static method? that way you won't have to pass `this` to the side-effect, the class can be abstract, and it will be more type-safe because you can't pass generic types to static methods in typescript.

**Comment by philipp-spiess** [comment]
Woohoo thanks @nataly87s for working on this! This issue is resolved now 🎉
