### ISSUE TITLE
Could not find a declaration file for module 'react-recomponent'

### ISSUE THREAD

**Issue by basbz** [philipp-spiess/react-recomponent#22]
First off all thanks for including the typescript types :+1:!
In my project they don't seem to be picked up out of the box.
What would be the best way to get them to work?

**Comment by basbz** [comment]
Also I'd love help out, let me know what I can do...

**Comment by philipp-spiess** [comment]
Hey Bas! Thanks for reaching out. 

What version are you running? The TypeScript definitions should be in `1.0.0-rc.3` and not in the stable release yet.

**Comment by basbz** [comment]
Hey, thanks for the swift response. 
It's all starting to make sense now...
I'll close this issue and play with the _rc_
Thanks!

**Comment by philipp-spiess** [comment]
Great! Let me know in here if it works for you so I feel more confident cutting the 1.0.0 release 🙂

**Comment by basbz** [comment]
Yes I will, thanks for make this happen!
