### ISSUE TITLE
Static reducer TypeScript annotations

### ISSUE THREAD

**Issue by basbz** [philipp-spiess/react-recomponent#24]
Currently when I annotate my static reducer with a State type I get an incompatibility error
```
error TS2417: Class static side 'typeof MyComponent' incorrectly extends base class static side 'typeof ReComponent'.                                                
  Types of property 'reducer' are incompatible.                                                                                                                                                                     
    Type '(action: Action, state: State) => NoUpdateAction' is not assignable to type '<TState, TAction extends Action, TSideEffect = any>(action: Action, state: TState) => ReducerAction<TState, TSideEffect>'.                           
      Types of parameters 'state' and 'state' are incompatible.                                                                                                                                                         
        Type 'TState' is not assignable to type 'State'.
```
I've tried to fix this myself by propagating the Component State to the reducer. But TypeScript doesn't allow that: `Static members cannot reference class type parameters.`

In the end it boils down to properly annotating the static reducer which is easier said then done:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16967
https://github.com/Microsoft/TypeScript/issues/13462

**Comment by basbz** [comment]
I'm preparing a PR with a work around, but it might be less than ideal

**Comment by philipp-spiess** [comment]
@basbz Did you had a chance to look into the issue already? No pressure, I'm just curious 🙂

**Comment by basbz** [comment]
@philipp-spiess  thanks for asking. Yeah I did, but I had some other stuff to work on this week. I want to start using from  ReComponent next week. So'll definitely come up with a PR soon!

**Comment by basbz** [comment]
@philipp-spiess really sorry about raising this issue. Spent some time on it again, and everything works as expected. Sorry if I delayed the release process :sweat:

**Comment by philipp-spiess** [comment]
That's totally fine! Thank you for coming back and confirming that everything works as intended.

**Comment by basbz** [comment]
If all goes well, we'll take it in production soon. So I'm sure to bring up other stuff if I run into it.
Thanks!

**Comment by philipp-spiess** [comment]
This is exciting! Keep me posted! 🙂
