### ISSUE TITLE
Hosted link not working

### ISSUE THREAD

**Issue by bikkimahato** [philipp-spiess/react-recomponent#25]
The hosted link [https://github.com/philipp-spiess/react-recomponent] is not working it is redirecting to the same page.
![image](https://user-images.githubusercontent.com/42492682/147831285-59f8ee32-c22c-4208-b92b-5c9114b71504.png)

**Comment by philipp-spiess** [comment]
Hey! There isn't really more to it, the readme is the only resource AFAIK. I haven't been working on this project for years though.
